openapi: 3.0.0
info:
  title: API Usuarios - Proyecto Final
  description: API para gestionar usuarios, login y validación de acceso usando DynamoDB.
  version: "1.0.0"
paths:
  /usuarios/crear:
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Usuario creado exitosamente

  /usuarios/login:
    post:
      summary: Login de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token generado exitosamente

  /usuarios/validar:
    post:
      summary: Validar token de acceso
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        '200':
          description: Token válido
