openapi: 3.0.0
info:
  title: API Usuarios - Proyecto Final
  version: 1.0.0
  description: API para gestionar usuarios, login y validaci칩n de acceso usando AWS Lambda y DynamoDB

paths:
  /usuarios/crear:
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id, password]
              properties:
                user_id:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        '200':
          description: Usuario creado exitosamente
        '400':
          description: Datos inv치lidos

  /usuarios/login:
    post:
      summary: Login de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id, password]
              properties:
                user_id:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token generado exitosamente
        '401':
          description: Credenciales incorrectas

  /usuarios/validar:
    post:
      summary: Validar token de acceso
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [token]
              properties:
                token:
                  type: string
      responses:
        '200':
          description: Token v치lido
        '401':
          description: Token inv치lido
